name: .NET Core Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:

  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: FlagsISO.sln
      App_Project_Directory_1: FlagsISO
      App_Project_Path_1: FlagsISO\FlagsISO.csproj

      App_Project_Directory_2: FlagsISO.EtoForms\FlagsISO.EtoForms
      App_Project_Path_2: FlagsISO.EtoForms\FlagsISO.EtoForms.csproj
      
      App_Project_Directory_3: FlagsISO.WinForms\FlagsISO.WinForms
      App_Project_Path_3: FlagsISO.WinForms\FlagsISO.WinForms.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET 6 workload
    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Create the FlagsISO app package by building and packaging the NuGet
    - name: Create the FlagsISO NuGet package
      run: msbuild $env:App_Project_Path_1 /p:Configuration=$env:Configuration

    # Create the FlagsISO.EtoForms app package by building and packaging the NuGet
    - name: Create the FlagsISO.EtoForms NuGet package
      run: msbuild $env:App_Project_Path_2 /p:Configuration=$env:Configuration
      
    # Create the FlagsISO.WinForms app package by building and packaging the NuGet
    - name: Create the FlagsISO.WinForms NuGet package
      run: msbuild $env:App_Project_Path_3 /p:Configuration=$env:Configuration
